version: '3.7'


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c "python3 manage.py migrate &&
             gunicorn ticket_management.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    # env_file: .env